### ISSUE TITLE
Using native WireGuard app for mobile clients.

### ISSUE THREAD

**Issue by kennyparsons** [netbirdio/netbird#213]
I really love Tailscale, except that the control server is not open source and that the iOS app is a huge battery drain. It does not implement on demand capabilities. I'm very interested in this project to replace it. 

Is it possible for a solution like this to generate the proper WireGuard config file to use with the WireGuard native iOS app?

So I have a finite amount of clients, say 10. I only have 2-3 that are truly mobile. Is a control server "check in" required to make it work? I'm unfamiliar with exactly how the mesh overlay is created and continuously updated for all other clients. I'm assuming a static WireGuard config would not be able to know if/when another client changes networks (dynamic ip, roaming, etc.)

As a consolation, I wonder if a static WireGuard config file could be downloaded, but options added to just connect to one "relay" server all the time and get its "mesh connectivity" from the relay, since it won't have constant updates from the control plane.

**Comment by HPPinata** [comment]
That's essentially what netmaker does to integrate unsupported clients (IoT, routers without plugins, currently mobile phones, etc.)
See https://www.netmaker.io/features/ingress

They don't get direct peer to peer connections (instead going through the ingress node and then that uses peer to peer), but it's a lot better than nothing and still more flexible than a traditional VPN server.

While netbird might get mobile clients soon I'd still love to see that feature, as I use quite a few external devices that have wireguard support, but can not run any custom/third party software at all...

**Comment by mlsmaycon** [comment]
Recently we've released the Android app: https://play.google.com/store/apps/details?id=io.netbird.client

The iOS app is under development and should be release in Q3

**Comment by ykorzikowski** [comment]
Any plans releasing a TestFlight release preview for ios?

**Comment by mlsmaycon** [comment]
Hello folks, you can sign up for the iOS preview here: https://forms.gle/HVAdMKt2vSdCiTzY9

We will send you test flight invites when the first version is ready for testing.

**Comment by mlsmaycon** [comment]
Hello folks, we published the iOS app!!!

You can find it here:
https://apps.apple.com/us/app/netbird-p2p-vpn/id6469329339

We are looking into, publishing to China's store but it might be a problem as it requires more paperwork. So it will be great to hear from the community there, if there is an alternative distribution channel.

**Comment by hwinkel** [comment]
but still having a gateway to plain WG clients like netmaker makes sense IMHO, please keep the non interactive users and devices in mind.
