### ISSUE TITLE
Netbird interface keeps flapping up and down

### ISSUE THREAD

**Issue by iball** [netbirdio/netbird#2173]
**Describe the problem**

Netbird interface keeps flapping up and down on Windows and Linux.

**To Reproduce**

1. Install Netbird
2. Watch it flap by constantly refreshing network interfaces at the command line. 

**Expected behavior**

I didn't expect v28 to blow everything up.  It's preventing me from getting to my services.

**Are you using NetBird Cloud?**

Yes.

**NetBird version**

27.10 on Windows but it does the same no matter which version I install.  28.2 on everything else.  Tried 28.2, 28.1, 28.0, and now 27.10 on the same Windows 11 PC but it's the same all over, constantly reconnecting to peers and the WT0 interface keeps disappearing and reappearing.  Same behavior on *all* my Netbird clients.

**NetBird status -d output:**

If applicable, add the `netbird status -d' command output.

No.  All it shows is a list of peers but it's constantly reconnecting to them all.

**Comment by pascal-fischer** [comment]
Hi @iball,
can you share [debug logs](https://docs.netbird.io/how-to/troubleshooting-client#debug-for-a-specific-time) of that peer?

**Comment by lixmal** [comment]
@iball this might be an issue with the network monitor. You can disable it for the time being, but please collect the debug logs.

```
netbird down
netbird up --network-monitor=false
```

**Comment by BizkitX** [comment]
We began experiencing the same issue once we upgraded from 27.10 to 28.2. I just tested changing the 'network monitor' to false and it appears to be stable at the moment. Unsure what function the network monitor is doing to break the connection.

**Comment by JonathanHohimer** [comment]
I'm also experiencing the same issue. With network monitor off, the issue doesn't happen.

**Comment by JonathanHohimer** [comment]
I ran the process in foreground and was pushing a lot of data through to get it to trigger. I get the following output:

`2024-06-22T20:08:50-05:00 INFO client/internal/networkmonitor/monitor_windows.go:131: network monitor: neighbor 10.210.0.1 () is not reachable: unreachable
2024-06-22T20:08:50-05:00 INFO client/internal/engine.go:1476: Network monitor detected network change, restarting engine
2024-06-22T20:08:50-05:00 INFO client/internal/engine.go:252: Network monitor: stopped`

And then it restarts the connection. This keeps happening even though nothing is changing. With network monitor disabled this doesn't happen.

**Comment by Hobby-Student** [comment]
I noticed the same behavior. Updated from v0.27.10 to v0.28.2 (Windows) and did a
`netbird up -N`

After
`netbird up --network-monitor=false`

everything is working as intended.

**Comment by raptaml** [comment]
Same Here:
`netbird up --network-monitor=false` solves the issue.
Another PC is running just fine.

**Comment by mlsmaycon** [comment]
Hey guys, the v0.28.3 will fix the issue on Windows with network monitor.

**Comment by mlsmaycon** [comment]
We released v0.28.3, which fixes the issue with the network monitor on Windows. Please upgrade and enable network monitor with:
```
netbird down
netbird up -N
```

**Comment by raptaml** [comment]
Confirmed, works just like before.
Thanks!

**Comment by pyfrancoeur** [comment]
Can confirm the issue is still present in 28.4. 
netbird up --network-monitor=false still fixes it for me though. What are the consequences of running this?
Thanks!

**Comment by mlsmaycon** [comment]
@pyfrancoeur can you enable network monitor for a brief period and run the following command to collect some logs to help us fix the issue?

```shell
netbird down
netbird up -N
netbird -A debug for 1m
```
After the tests are done you can disable the monitor with:
```shell
netbird down
netbird up --network-monitor=false
```
Besides that, any information about your setup will be helpful, e.g., number of active interfaces, OS, and main connection type (wifi or cable)

**Comment by lixmal** [comment]
Could any of you test the network monitor change from https://github.com/netbirdio/netbird/pull/2450?

1. Grab the binaries from https://github.com/netbirdio/netbird/actions/runs/10459247214?pr=2450
2. Extract `windows-packages.zip`
3.
```
netbird service stop
netbird service uninstall
```

4. Move `netbird.exe` from the zip archive to `%PROGRAMFILES%/Netbird`

5.
```
netbird service install
netbird service start
netbird down
netbird up --network-monitor=true
```

**Comment by lixmal** [comment]
This is in the `0.28.8` release. If it fixes the issue, please close.

**Comment by Hobby-Student** [comment]
@lixmal I have had no free time to test, but I will soon configure my Laptop accordingly and will report back.
