### ISSUE TITLE
Dockerhub verified images;  join Slack link on website is expired

### ISSUE THREAD

**Issue by ajhindle** [netbirdio/netbird#2905]
Hi

Q1
I looked at the https://hub.docker.com/r/netbirdio/netbird - there is nothing about the Netbird organisation or being a verified publisher or image scanning.  
Is this an official source managed by Netbird?  If yes, are there plans to change anything there?

Q2
There is an expired [join link](https://join.slack.com/t/netbirdio/shared_invite/zt-2p5zwhm4g-8fHollzrQa5y4PZF5AEpvQ) to a Netbird support channel in Slack on the [Netbird website](https://netbird.io/)
Is the Slack channel still accepting new users?

Thanks

**Comment by mgarces** [comment]
Hi @ajhindle thank you for your suggestion, we will look into it. 
Regarding the expired Slack link, we've fixed this last week, can you please give it another try?

**Comment by kristoffn** [comment]
I want to bump this issue, the Slack invite link is still broken.
