### ISSUE TITLE
Windows Client Error: rpc error: code = PermissionDenied desc = invalid user

### ISSUE THREAD

**Issue by samf-acacia** [netbirdio/netbird#3158]
**Describe the problem**

A subset of Windows 11 users in our environment are having trouble connecting to our self-hosted Netbird instance. We also run Ubuntu Desktop clients, but this issue doesn't affect those devices. We run Microsoft Entra-ID for SAML/SSO authentication to connect.

When a user (who is having the issue) attempts to connect to the Netbird from Windows, they are forwarded to the Entra login page and manage to successfully authenticate, and are presented with the "Login Successful" page from Netbird. After about 15-20 seconds Netbird time out and they get the error:

rpc error: code = PermissionDenied desc = invalid user

Tried to search past issues, but couldn't find anything related to this specific issue.

The user does show up in the Management portal (successful login??) of our instance, tried removing and reconnecting, but that didn't work.

**To Reproduce**

1. Go to Netbird VPN client and attempt to connect
2. Log in using Entra ID credentials
3. Wait 15-20 seconds for the client to time out
4. See error rpc error: code = PermissionDenied desc = invalid user

**Expected behavior**

A successful connection to our Netbird instance since it shows Login Successful.

**Are you using NetBird Cloud?**

Self hosting Netbird

**NetBird version**

v0.35.2 on Server and Clients

**Do you face any (non-mobile) client issues?**

This is specifically a Windows 11 client issue

**Screenshots**

![image](https://github.com/user-attachments/assets/4a2c2f9c-97d4-4c4a-8980-72e8f52c971c)

**Comment by d-givens** [comment]
Having the exact same problem with one user. Entra ID. Self-hosted. Same issues.

**Comment by d-givens** [comment]
> I had the same issue in the free tier, but it seemed like the issue was caused by the user's machine itself. The user's machine was included in another free tier group, having that machine removed everywhere else except my group fixed the issue. Maybe if a machine is included in a free tier it can't be included elsewhere?

We're both self-hosted instead of free tier.

**Comment by K0-RR** [comment]
I'm having the same issue on Ubuntu 22.04 (free tier) so it's not Windows-related.

**Comment by samf-acacia** [comment]
@d-givens The exact same problem.............

Except 3 users in about 20 users see this problem.

**Comment by sergeycherepanov** [comment]
macos - same issue

**Comment by samf-acacia** [comment]
> macos - same issue, the issue appears in case when the same peer already exists by another user. In my case I was authenticated as admin previously.

Yeah we tried this but were still getting the same error :(

**Comment by bsmithuk** [comment]
Fix for me was absolutely nuking the install and rm any directories connected to netbird and disconnecting tailscale. Fixed it for me.

**Comment by d-givens** [comment]
> Fix for me was absolutely nuking the install and rm any directories connected to netbird and disconnecting tailscale. Fixed it for me.

This is on the client side that you're removing the install?

**Comment by bsmithuk** [comment]
Yep correct removed client install completely

**Comment by samf-acacia** [comment]
> Yep correct removed client install completely
> […](#)

I've actually tried this and it worked briefly but after a day it started happening again.

**Comment by Phillipjacob** [comment]
Same issue OSX, self hosted with zitadel and google workspace, it only appears when using google login.

**Comment by wldhg** [comment]
Same issue (Windows 11), in the team plan. Resolved by restarting netbird app.

**Comment by caa** [comment]
Same issue on Windows 11, Netbird agent version 0.36.7 doing a test rollout on the free hosted plan. Reinstalling the Netbird agent didn't work. Uninstalling the agent, deleting _C:\ProgramData\Netbird_, then installing the agent allowed the user's account to connect successfully.

<img width="437" alt="Image" src="https://github.com/user-attachments/assets/ad8992b3-7634-4d61-8317-f9f89f5fe905" />

<img width="283" alt="Image" src="https://github.com/user-attachments/assets/b8e645b3-060e-4364-be0e-92d6e410a74e" />

**Comment by mlsmaycon** [comment]
The invalid user issue happens when you try to authenticate an existing peer using a different user. This is common when you have a shared computer or a personal and company NetBird account. Can you please review that and confirm that this is not the case?

**Comment by caa** [comment]
I'm 99% sure that this is what happened. User A signed in with their OS user account and their Netbird account on this peer (computer). Then User B sign in with a different OS user account and their Netbird account on this same peer, which is why the get the _invalid user_ error.

> The invalid user issue happens when you try to authenticate an existing peer using a different user. This is common when you have a shared computer or a personal and company NetBird account. Can you please review that and confirm that this is not the case?

I think it would make sense to put the config files in `C:\Users\Username\AppData` rather than `C:\ProgramData\Netbird`. I know that this would require a lot of changes. For instance, which Netbird account should be used after a reboot?

> So it is only possible to have one account on a machine ?

**Comment by MYMaj** [comment]
That worked for me too
> I'm 99% sure that this is what happened. User A signed in with their OS user account and their Netbird account on this peer (computer). Then User B signed in with a different OS user account and their Netbird account on this same peer, which is why they got the _invalid user_ error.
> 
> > The invalid user issue happens when you try to authenticate an existing peer using a different user. This is common when you have a shared computer or a personal and company NetBird account. Can you please review that and confirm that this is not the case?
> 
> I think it would make sense to put the config files in `C:\Users\Username\AppData` rather than `C:\ProgramData\Netbird`. I know that this would require a lot of changes. For instance, which Netbird account should be used after a reboot?
> 
> > So it is only possible to have one account on a machine ?

**Comment by mashraf92** [comment]
I am also encountering this persistent configuration issue on my macOS device. Despite a full uninstallation of the Netbird agent and manual removal of its configuration files, the problem remains.

Separately, other devices are successfully connecting to my network, but they are not appearing in the peer list on the app.netbird.io dashboard. I would like to know if this peer visibility problem is related to the above mentioned issue.

**Comment by nazarewk** [comment]
@mashraf92 
> I am also encountering this persistent configuration issue on my macOS device. Despite a full uninstallation of the Netbird agent and manual removal of its configuration files, the problem remains.

Are you sure you did all of the following?
1. `netbird service stop`
2. remove `/etc/netbird/config.json`
3. `netbird service start`

I've added more explicit instructions to the docs https://github.com/netbirdio/docs/pull/379

> Separately, other devices are successfully connecting to my network, but they are not appearing in the peer list on the app.netbird.io dashboard. I would like to know if this peer visibility problem is related to the above mentioned issue.

Are you an `Admin`/`Owner` of the account? Do you have access to the full dashboard at all?

If you are an `Admin` and you're not seeing the Peers it most likely means the users are logging in to a different NetBird account than you do.

If you are just a regular `User` you will only see your own Peers in the Dashboard.

**Comment by DiyRex** [comment]
Netbird Peer Conflict Fix (Client Side)

sudo rm /etc/netbird/config.json
sudo rm -rf ~/.netbird/
sudo rm -rf /var/lib/netbird/
sudo rm -rf /Library/Application\ Support/netbird/

then up netbird again


this worked for me.

**Comment by mashraf92** [comment]
Still stuck on this even though I signed on different devices with same credentials `Admin` On other devices I signed in to same account but this screen is stuck on app.netbird.io.

Also I tried to the above shared steps and the issue is resolved but not able to see the device as peer in the dashboard

![Image](https://github.com/user-attachments/assets/e7ccb380-1fa8-4c66-9998-480b4dfc61be)

**Comment by mlsmaycon** [comment]
@mashraf92 it seems like this email address has user role in the account. If you are using NetBird cloud you can send an email to support@netbird.io for us to check.

**Comment by jin-li** [comment]
> Netbird Peer Conflict Fix (Client Side)
> 
> sudo rm /etc/netbird/config.json; sudo rm -rf ~/.netbird/; sudo rm -rf /var/lib/netbird/; sudo rm -rf /Library/Application\ Support/netbird/
> 
> then up netbird again
> 
> this worked for me.

This works for me on Linux! After uninstall, delete config directory and re-install, it worked.

But I think the issue still need to be fixed.

1. After the login expired, it seems there's no way to clear the old login from the client command. I tried `netbird deregister`, `netbird profile remove default`, neither worked. 
2. At first I didn't find where the configuration file/directory is located. I thought it might be in `/etc/netbird`, but it's not. Finally, I found this discussion and found the configuration is at `/var/lib/netbird`. Should the netbird client provide a command like `netbird config list` to list where the configuration file(s) are located?
3. It seems netbird client allow multiple profiles (`netbird profile` command), however, after the current login expired, it's still not possible to login another user. This is very confusing.
