### ISSUE TITLE
Exclude routing peer public IP from routes

### ISSUE THREAD

**Issue by eveyraud** [netbirdio/netbird#4069]
**Is your feature request related to a problem? Please describe.**
Refering to ticket #4047 :
When a NetBird network route or exit node is configured to include the routing peer's public IP address, a direct P2P connection fails. This happens because WireGuard attempts to route traffic destined for the routing peer's public IP back into the VPN tunnel managed by that same peer. Consequently, P2P connectivity cannot be sustained, and NetBird falls back to using the TCP relay, degrading performances.

**Describe the solution you'd like**
Exclude the routing peer's public IP from the route added to the system

**Describe alternatives you've considered**
Add an option to exclude the routing peer's public IP in the network definition

**Additional context**
None

**Comment by nazarewk** [comment]
I'm pretty sure determining all of the Peer's externally accessible IPs is non-trivial (some customers have 2 or more uplinks, multiple VLANs joined indirectly through routers etc.), but maybe we could allow the user to specify a set of IP ranges + interface pairs to force local routing through?

**Comment by eveyraud** [comment]
> I'm pretty sure determining all of the Peer's externally accessible IPs is non-trivial (some customers have 2 or more uplinks, multiple VLANs joined indirectly through routers etc.), but maybe we could allow the user to specify a set of IP ranges + interface pairs to force local routing through?

You are right, I hadn't considered those types of infrastructure setups. However, are you suggesting that this would need to be specified client-side? I think it would be better managed server-side. Maybe don't I understand the implications of such a request so feel free to correct me if I'm wrong. 

Thanks for your help

**Comment by saule1508** [comment]
that is one reason why the exit node is not working for us, all the connections become relayed. We could add routing on the client to make sure routing peers public IP and stun IP gets routed outside the vpn tunnel, but it is cumbersome and error prone. It would be nice if the exit node set-up would allow to exclude IP's ?

**Comment by lixmal** [comment]
Hey folks, could you please test https://github.com/netbirdio/netbird/releases/tag/v0.51.2 and report whether the issue has been resolved for you?

**Comment by eveyraud** [comment]
Fixed, thanks !

**Comment by Blackclaws** [comment]
@lixmal As others have mentioned in the linked issue, this isn't actually solved for many people. Having an exit node within a network instead of a server with a public ip address causes whatever detection mechanism was implemented to not properly work. Meaning exit nodes continue to get relayed connections once the route gets pushed.
