### ISSUE TITLE
netbird_installer_0.59.1_windows_amd64.{msi,exe} not signed

### ISSUE THREAD

**Issue by Frooastside** [netbirdio/netbird#4576]
**Describe the problem**

The installers of the latest version are not signed

**To Reproduce**

1. Go to https://github.com/netbirdio/netbird/releases
2. Download netbird_installer_0.59.1_windows_amd64.msi or netbird_installer_0.59.1_windows_amd64.exe
3. Right Click -> Properties -> Digital signatures

**Expected behavior**

Signed Installer

(netbird_installer_0.59.0_windows_amd64.exe)
<img width="392" height="489" alt="Image" src="https://github.com/user-attachments/assets/38a322b7-b44a-4532-9847-13a8d3940dc1" />

**Screenshots**

(netbird_installer_0.59.1_windows_amd64.exe)
<img width="396" height="472" alt="Image" src="https://github.com/user-attachments/assets/d33f826d-9adb-4dad-9fd0-95561a9304b0" />

**Comment by nazarewk** [comment]
It should be resolved now. Can you confirm?

**Comment by matt-shelley-IT** [comment]
@nazarewk I just checked and it is not resolved, still no signature.  The binaries in https://github.com/netbirdio/netbird/releases/tag/v0.59.1 were what I downloaded, https://github.com/netbirdio/netbird/releases/download/v0.59.1/netbird_installer_0.59.1_windows_amd64.exe specifically.

**Comment by mlsmaycon** [comment]
@matt-shelley-IT, we had an issue with the automated signing service provider. The 0.59.2 release is fine now and our validation confirmed that all installers are signed.
