### ISSUE TITLE
Windows AD DC ignores netbird search domain

### ISSUE THREAD

**Issue by bbaumgartl** [netbirdio/netbird#987]
It seems like that the netbird search domain is ignored on a Windows Server Active Directory Domain Controller.

After connecting netbird the log states that the search domain was added:
```
2023-06-23T11:44:27+02:00 INFO client/internal/dns/host_windows.go:181: updated the search domains in the registry with 1 domains. Domain list: [netbird.cloud]
```
But it does not show up in `ipconfig /all` under `DNS Suffix Search List` or `Connection-specific DNS Suffix`:
```
Windows IP Configuration

   Host Name . . . . . . . . . . . . : windows-server
   Primary Dns Suffix  . . . . . . . : domain.local
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : domain.local

Unknown adapter wt0:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : WireGuard Tunnel
   Physical Address. . . . . . . . . :
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 100.71.19.142(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 162275179
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-22-98-15-90-AC-1F-6B-60-F5-72
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```
And DNS queries with only the hostname fail:
```powershell
PS C:\Users\administrator> Resolve-DnsName -Name peer-a
Resolve-DnsName : peer-a : DNS name does not exist
At line:1 char:1
+ Resolve-DnsName -Name  peer-a
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (peer-a:String) [Resolve-DnsName], Win32Exception
    + FullyQualifiedErrorId : DNS_ERROR_RCODE_NAME_ERROR,Microsoft.DnsClient.Commands.ResolveDnsName
```
Using the FQDN does work though:
```powershell
PS C:\Users\administrator> Resolve-DnsName -Name peer-a.netbird.cloud
Name                                           Type   TTL   Section    IPAddress
----                                           ----   ---   -------    ---------
peer-a.netbird.cloud                           A      300   Answer     100.71.126.42
```

**Comment by bbaumgartl** [comment]
I tried the same configuration on a AD joined Windows 10 machine. DNS resolution for netbird works, but the local AD domain doesn't work anymore. It seems to me that netbird replaces the `DNS Suffix Search List` with the netbird search domain while the `Primary Dns Suffix` stays the same (local AD domain). After disconnecting netbird the original local AD domain gets restored as search domain. Since we don't see the same behaviour on the AD DC maybe replacing the `DNS Suffix Search List` is not allowed there. Is it possible to add the search domain to the list instead of replacing it? I think this will benefit normal Windows clients too (local hostname resolution still works after connecting to netbird).

**Comment by bbaumgartl** [comment]
Another thing i noticed is that connecting netbird registers the netbird IP address in the local DNS server. This causes local network clients to sometimes get the netbird IP instead of the local IP and thus can't connect to the server. There is an option in the adapter properties (`Register this connection's addresses in DNS`) which should avoid this.

<img width="508" alt="image" src="https://github.com/netbirdio/netbird/assets/14923000/9a14569e-a162-4105-a898-f03278106816">

**Comment by MobileManiC** [comment]
Yes, waiting for that fix as well... This makes NetBird effectively unusable in AD environment, because short names are usually heavily utilized in avarage business usecases (seems that even some Win10/11 domain communication itself expects AD servers to be accessible by their short name).

**Comment by MobileManiC** [comment]
Btw. I think the solution 1. (`"Append primary and connection specific DNS suffixes"`) is proper one

**Comment by hesshaus** [comment]
Can confirm this is an issue in AD environments. The suggestions above did fix these issues, however, they are temporary (upon reboot or restarting the netbird client). Would love to roll this solution out but this is a major hurdle.

**Comment by MobileManiC** [comment]
I think this is already resolved for a long time. Have you tried to install current version and configure DNS properly on the server side?

**Comment by bbaumgartl** [comment]
I just briefly checked it and it seems that the first two points (windows server netbird dns resolution, ad joined windows machine local dns resolution) seem to work now.

The third point (netbird ip is registered in the local domain as ip address) seems to be still an issue.

**Comment by florian-obradovic** [comment]
"The third point (netbird ip is registered in the local domain as ip address) seems to be still an issue."
This is standard behaviour for windows: https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/enable-disable-dns-dynamic-registration
"Windows supports Domain Name System (DNS) updates per RFC 2136. By default, this behavior is enabled for Windows DNS clients."

You could disable this via GPO:
Computer Configuration > Administrative Templates > Network > DNS Client > **Dynamic Update** 
Set it to disabled:
![CleanShot 2024-10-12 at 14 55 04@2x](https://github.com/user-attachments/assets/9ddc080d-4b25-4f70-a3c5-184545d55918)

**Comment by florian-obradovic** [comment]
I came across this issue and have the same issue on all AD joined machines (Windows 10/11, Server OS).
All Netbird specific DNS settings are ignored on AD joined or Entra-ID hybrid joined machines. WORKGROUP or Entra-ID only joined machines work fine.

Looks like the NRPT Rules are ignored: `Get-DnsClientNrptRule`
![CleanShot 2024-10-12 at 16 06 16@2x](https://github.com/user-attachments/assets/7ad48dd2-be3e-40e9-9c47-1566c8e5df97)

- the default dns search domain, in my case onetpg (Example: server01.onetpg) isn't working
- ![CleanShot 2024-10-12 at 16 08 24@2x](https://github.com/user-attachments/assets/555586db-ea5e-4463-a108-2dd23e412142)

- Added nameservers like this:
![CleanShot 2024-10-12 at 16 05 10@2x](https://github.com/user-attachments/assets/7cde5adc-3c7f-430f-b44b-30bc6de84b5d)

nslookup or Resolve-DnsName work if you specify the Netbird default DNS IP:
![CleanShot 2024-10-12 at 16 07 27@2x](https://github.com/user-attachments/assets/cc56c550-2ab4-4677-bcbb-0e5ba9cc1619)

It works on machines without domain join:
![CleanShot 2024-10-12 at 16 09 32@2x](https://github.com/user-attachments/assets/098faa89-547c-4de0-98f9-0bfaa26fff79)

**Comment by florian-obradovic** [comment]
I found some hints in a [Tailscale issue](https://github.com/tailscale/tailscale/issues/4607).

The Nrpt-Rule Netbird creates, is ignored if you have _**any**_ DNS settings / policies applied which is literally the default in every Active Directory domain.
Check if you have the key _HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient_ with any settings in place:
![CleanShot 2024-10-12 at 20 20 04@2x](https://github.com/user-attachments/assets/ecbefb4b-aab7-454c-bb4f-18d6b34d6928)


If so, the NrptRule is ignored (_Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DnsPolicyConfig\NetBird-Match_)
![CleanShot 2024-10-12 at 20 12 20@2x](https://github.com/user-attachments/assets/1d5093b2-af61-4fb2-8b58-e1039237d7d6)

**Steps to test:**
1. Backup and delete the full key _HKLM\SOFTWARE\Policies\Microsoft\Windows NT\**DNSClient**__
2. make sure no network is connect which to the AD to avoid the GPOs getting re-applied :)
3. disconnect Netbird, restart the service `Restart-Service Netbird` or reboot the machine
4. connect Netbird and DNS is working ✅
![CleanShot 2024-10-12 at 20 26 33@2x](https://github.com/user-attachments/assets/00d10302-61cd-4dc8-8dfd-bd3a50aa3383)

**Possible solution**
Creating DNS Client NRPT Rule like this doesn't work:
```
Add-DnsClientNrptRule -Namespace "onetpg" -NameServers "100.116.255.254"
Get-DnsClientNrptRule -Name "{265F11C4-B797-48F6-BF9D-24CFD59DC369}"
```

I think we need a DnsClientNrptPolicy I think but I'm unsure how to create them correctly... there is no Add-DnsClientNrpt**Policy** commandlet

I created registry key manually and it works :)
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig\{Netbird-onetpg}]
"ConfigOptions"=dword:00000008
"Name"=hex(7):2e,00,6f,00,6e,00,65,00,74,00,70,00,67,00,00,00,00,00
"IPSECCARestriction"=""
"GenericDNSServers"="100.116.255.254"
"Version"=dword:00000002
```
![CleanShot 2024-10-12 at 20 45 03@2x](https://github.com/user-attachments/assets/79bb6fcf-de80-4186-8b09-23459501741b)


@mlsmaycon: Let's dig deeper and find out how the Tailscale folks have fixed it: https://github.com/tailscale/tailscale/issues/4607

**Infos**
- Microsoft: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-gpnrpt/8cc31cb9-20cb-4140-9e85-3e08703b4745
- Microsoft: https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-GPNRPT/%5bMS-GPNRPT%5d.pdf
- Tailscale: https://github.com/tailscale/tailscale/commit/4d0d4e0b69cde02b6e9b3191e3ffa1eaacbe0202
- Tailscale: https://github.com/tailscale/tailscale/pull/11684
- Tailscale comment: https://github.com/tailscale/tailscale/issues/4607#issuecomment-1119146501

**Comment by florian-obradovic** [comment]
@mlsmaycon did you have a chance to look at this?
I bet this could block a rollout for many corps with Windows environments.

**Comment by lixmal** [comment]
`100.116.255.254` is correct. It's netbird's fake dns IP, the configured dns servers will be set as upstream internally. See `netbird status -d`

**Comment by florian-obradovic** [comment]
Thanks @lixmal !

**Comment by jackmusick** [comment]
Bumping this, though I'm still experimenting. I've tried a lot of these suggestions. Basically what I'm experiencing is that I can't ping by name once joined to the domain. Is there a recommended setup here to avoid setting up a routing peer, or is this still an issue?

**Comment by flotpg** [comment]
@lixmal awesome work ❤️❤️❤️
It's working for most records but there seems to be an issue with public resolvable records - in my case *.az.ontpg.com
![Image](https://github.com/user-attachments/assets/9d955893-57cd-42b1-b304-0535703490ff)
![Image](https://github.com/user-attachments/assets/3cd954de-0fe6-4a2f-a4e3-c7e3b1ac7614)

MS Edge:
![Image](https://github.com/user-attachments/assets/be68396e-9077-4b40-b86a-5beab93c4389)

So it looks like resolve-dnsname works but anything else doesn't use the dns server. Feel free to reach me on slack for a debug session. Eve

From a domain / hybrid joined machine:
```
 ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : vWin11-KES01
   Primary Dns Suffix  . . . . . . . : domain.tpg.local
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : domain.tpg.local
                                       other.tpg.local
                                       another.tpg.local
                                       another.tpg.local

Unknown adapter wt0:

   Connection-specific DNS Suffix  . : onetpg
   Description . . . . . . . . . . . : WireGuard Tunnel
   Physical Address. . . . . . . . . :
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 100.116.147.121(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
   NetBIOS over Tcpip. . . . . . . . : Enabled
   Connection-specific DNS Suffix Search List :
                                       onetpg

Ethernet adapter FritzBox:

   Connection-specific DNS Suffix  . : fritz.box
   Description . . . . . . . . . . . : Microsoft Hyper-V Network Adapter #2
   Physical Address. . . . . . . . . : 00-15-5D-7A-70-AC
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::a8f6:1589:3819:afc9%13(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.178.36(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Donnerstag, 13. Februar 2025 22:41:52
   Lease Expires . . . . . . . . . . : Sonntag, 23. Februar 2025 22:41:52
   Default Gateway . . . . . . . . . : 192.168.178.1
   DHCP Server . . . . . . . . . . . : 192.168.178.1
   DHCPv6 IAID . . . . . . . . . . . : 486544733
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-2B-FE-A6-2B-00-1D-D8-B7-1D-28
   DNS Servers . . . . . . . . . . . : 192.168.178.1
   NetBIOS over Tcpip. . . . . . . . : Enabled

PS C:\Users\floriano> Get-DnsClientGlobalSetting


UseSuffixSearchList : True
SuffixSearchList    : {domain.tpg.local, other.tpg.local, another.tpg.local, another.tpg.local}
UseDevolution       : True
DevolutionLevel     : 0



PS C:\Users\floriano> Get-DnsClientNrptGlobal

EnableDAForAllNetworks QueryPolicy SecureNameQueryFallback
---------------------- ----------- -----------------------
Disable                Disable     Disable


PS C:\Users\floriano> Get-DnsClientNrptRule


Name                             : VPN_AUTO_TPG AlwaysOn VPN v1.4_4f69d45d-1e6f-488c-973a-5b61e4ed611e
Version                          : 2
Namespace                        : {_ldap}
IPsecCARestriction               :
DirectAccessDnsServers           :
DirectAccessEnabled              : False
DirectAccessProxyType            :
DirectAccessProxyName            :
DirectAccessQueryIPsecEncryption :
DirectAccessQueryIPsecRequired   :
NameServers                      : {172.17.111.333, 172.17.111.444}
DnsSecEnabled                    : False
DnsSecQueryIPsecEncryption       :
DnsSecQueryIPsecRequired         :
DnsSecValidationRequired         :
NameEncoding                     : Disable
DisplayName                      :
Comment                          :

Name                             : VPN_AUTO_TPG AlwaysOn VPN v1.4_8a3a0cc6-a3ec-4410-a9cb-d7866c0eff3f
Version                          : 2
Namespace                        : {wpad}
IPsecCARestriction               :
DirectAccessDnsServers           :
DirectAccessEnabled              : False
DirectAccessProxyType            :
DirectAccessProxyName            :
DirectAccessQueryIPsecEncryption :
DirectAccessQueryIPsecRequired   :
NameServers                      : {172.17.111.333, 172.17.111.444}
DnsSecEnabled                    : False
DnsSecQueryIPsecEncryption       :
DnsSecQueryIPsecRequired         :
DnsSecValidationRequired         :
NameEncoding                     : Disable
DisplayName                      :
Comment                          :

Name                             : VPN_AUTO_TPG AlwaysOn VPN v1.4_ac72b6f3-8bd8-45a3-93a1-65b11a42482d
Version                          : 2
Namespace                        : {isatap}
IPsecCARestriction               :
DirectAccessDnsServers           :
DirectAccessEnabled              : False
DirectAccessProxyType            :
DirectAccessProxyName            :
DirectAccessQueryIPsecEncryption :
DirectAccessQueryIPsecRequired   :
NameServers                      : {172.17.111.333, 172.17.111.444}
DnsSecEnabled                    : False
DnsSecQueryIPsecEncryption       :
DnsSecQueryIPsecRequired         :
DnsSecValidationRequired         :
NameEncoding                     : Disable
DisplayName                      :
Comment                          :



PS C:\Users\floriano> Get-DnsClientNrptPolicy


Namespace                        : .onetpg
QueryPolicy                      :
SecureNameQueryFallback          :
DirectAccessIPsecCARestriction   :
DirectAccessProxyName            :
DirectAccessDnsServers           :
DirectAccessEnabled              :
DirectAccessProxyType            : NoProxy
DirectAccessQueryIPsecEncryption :
DirectAccessQueryIPsecRequired   : False
NameServers                      : 100.116.255.254
DnsSecIPsecCARestriction         :
DnsSecQueryIPsecEncryption       :
DnsSecQueryIPsecRequired         : False
DnsSecValidationRequired         : False
NameEncoding                     : Utf8WithoutMapping

Namespace                        : .another.tpg.local
QueryPolicy                      :
SecureNameQueryFallback          :
DirectAccessIPsecCARestriction   :
DirectAccessProxyName            :
DirectAccessDnsServers           :
DirectAccessEnabled              :
DirectAccessProxyType            : NoProxy
DirectAccessQueryIPsecEncryption :
DirectAccessQueryIPsecRequired   : False
NameServers                      : 100.116.255.254
DnsSecIPsecCARestriction         :
DnsSecQueryIPsecEncryption       :
DnsSecQueryIPsecRequired         : False
DnsSecValidationRequired         : False
NameEncoding                     : Utf8WithoutMapping

Namespace                        : .another.tpg.local
QueryPolicy                      :
SecureNameQueryFallback          :
DirectAccessIPsecCARestriction   :
DirectAccessProxyName            :
DirectAccessDnsServers           :
DirectAccessEnabled              :
DirectAccessProxyType            : NoProxy
DirectAccessQueryIPsecEncryption :
DirectAccessQueryIPsecRequired   : False
NameServers                      : 100.116.255.254
DnsSecIPsecCARestriction         :
DnsSecQueryIPsecEncryption       :
DnsSecQueryIPsecRequired         : False
DnsSecValidationRequired         : False
NameEncoding                     : Utf8WithoutMapping

Namespace                        : .other.tpg.local
QueryPolicy                      :
SecureNameQueryFallback          :
DirectAccessIPsecCARestriction   :
DirectAccessProxyName            :
DirectAccessDnsServers           :
DirectAccessEnabled              :
DirectAccessProxyType            : NoProxy
DirectAccessQueryIPsecEncryption :
DirectAccessQueryIPsecRequired   : False
NameServers                      : 100.116.255.254
DnsSecIPsecCARestriction         :
DnsSecQueryIPsecEncryption       :
DnsSecQueryIPsecRequired         : False
DnsSecValidationRequired         : False
NameEncoding                     : Utf8WithoutMapping

Namespace                        : .domain.tpg.local
QueryPolicy                      :
SecureNameQueryFallback          :
DirectAccessIPsecCARestriction   :
DirectAccessProxyName            :
DirectAccessDnsServers           :
DirectAccessEnabled              :
DirectAccessProxyType            : NoProxy
DirectAccessQueryIPsecEncryption :
DirectAccessQueryIPsecRequired   : False
NameServers                      : 100.116.255.254
DnsSecIPsecCARestriction         :
DnsSecQueryIPsecEncryption       :
DnsSecQueryIPsecRequired         : False
DnsSecValidationRequired         : False
NameEncoding                     : Utf8WithoutMapping

Namespace                        : .az.ontpg.com
QueryPolicy                      :
SecureNameQueryFallback          :
DirectAccessIPsecCARestriction   :
DirectAccessProxyName            :
DirectAccessDnsServers           :
DirectAccessEnabled              :
DirectAccessProxyType            : NoProxy
DirectAccessQueryIPsecEncryption :
DirectAccessQueryIPsecRequired   : False
NameServers                      : 100.116.255.254
DnsSecIPsecCARestriction         :
DnsSecQueryIPsecEncryption       :
DnsSecQueryIPsecRequired         : False
DnsSecValidationRequired         : False
NameEncoding                     : Utf8WithoutMapping


PS C:\Users\floriano> Get-ChildItem -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DnsPolicyConfig"


    Hive: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DnsPolicyConfig


Name                           Property
----                           --------
VPN_AUTO_TPG AlwaysOn VPN v1.4 Name              : {_ldap}
_4f69d45d-1e6f-488c-973a-5b61e ConfigOptions     : 8
4ed611e                        Version           : 2
                               GenericDNSServers : 172.17.111.333;172.17.111.444
                               VPNRequired       : 0
                               ProxyType         : 3
VPN_AUTO_TPG AlwaysOn VPN v1.4 Name              : {wpad}
_8a3a0cc6-a3ec-4410-a9cb-d7866 ConfigOptions     : 8
c0eff3f                        Version           : 2
                               GenericDNSServers : 172.17.111.333;172.17.111.444
                               VPNRequired       : 0
                               ProxyType         : 3
VPN_AUTO_TPG AlwaysOn VPN v1.4 Name              : {isatap}
_ac72b6f3-8bd8-45a3-93a1-65b11 ConfigOptions     : 8
a42482d                        Version           : 2
                               GenericDNSServers : 172.17.111.333;172.17.111.444
                               VPNRequired       : 0
                               ProxyType         : 3


PS C:\Users\floriano> Get-ChildItem -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig"


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig


Name                           Property
----                           --------
NetBird-Match                  Version           : 2
                               Name              : {.az.ontpg.com, .domain.tpg.local, .other.tpg.local, .another.tpg.local...}
                               GenericDNSServers : 100.116.255.254
                               ConfigOptions     : 8

```

**Comment by jbford1919** [comment]
I'm using Netbird to connect domain joined windows PC to our domain controllers through a routing peer with success.  The latest version works for me as long as I have a namserver group that as "ALL" domains captured. Previously I just had one nameserver group that matched our local domain but DNS to local domain stopped working. However, after adding a second nameserver group to capture ALL domains the issue was resolved.  Now my domain joined windows PC work as expected resolving DNS.

To be clear, I don't have netbird on my DC's. I use routing peer and have DC's listed as resources in Networks.

**Comment by saule1508** [comment]
Not working for me and my colleagues, it is broken since 0.36.7

https://github.com/netbirdio/netbird/issues/3332

PS C:\Windows\System32\WindowsPowerShell\v1.0> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : WL-BFVVDL3
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : elisa.net
                                       fr01.awl.mycorporate.net
                                       deac.awl.mycorporate.net
                                       wl.corp-group.net

Ethernet adapter Ethernet:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) Ethernet Connection (13) I219-LM
   Physical Address. . . . . . . . . : 00-BE-43-21-ED-ED
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter Ethernet 8:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Realtek USB GbE Family Controller #2
   Physical Address. . . . . . . . . : 00-BE-43-21-ED-EE
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Unknown adapter wt0:

   Connection-specific DNS Suffix  . : netbird.giservices
   Description . . . . . . . . . . . : WireGuard Tunnel
   Physical Address. . . . . . . . . :
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 100.67.175.125(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :
   NetBIOS over Tcpip. . . . . . . . : Enabled
   Connection-specific DNS Suffix Search List :
                                       netbird.giservices

Wireless LAN adapter Local Area Connection* 1:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter
   Physical Address. . . . . . . . . : F0-57-A6-7C-54-67
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Local Area Connection* 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Wi-Fi Direct Virtual Adapter #2
   Physical Address. . . . . . . . . : F2-57-A6-7C-54-66
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Ethernet adapter Ethernet 2:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Fortinet Virtual Ethernet Adapter (NDIS 6.30)
   Physical Address. . . . . . . . . : 00-09-0F-FE-00-01
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes

Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Intel(R) Wi-Fi 6 AX201 160MHz
   Physical Address. . . . . . . . . : F0-57-A6-7C-54-66
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::b2e5:c493:5d45:af3a%20(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.171.81.29(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Tuesday, 25 February 2025 09:23:57
   Lease Expires . . . . . . . . . . : Wednesday, 26 February 2025 09:23:57
   Default Gateway . . . . . . . . . : 10.171.81.1
   DHCP Server . . . . . . . . . . . : 10.171.81.1
   DHCPv6 IAID . . . . . . . . . . . : 133191590
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-29-A0-72-A9-00-BE-43-21-ED-ED
   DNS Servers . . . . . . . . . . . : 10.173.173.173
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter Bluetooth Network Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Bluetooth Device (Personal Area Network)
   Physical Address. . . . . . . . . : F0-57-A6-7C-54-6A
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
PS C:\Windows\System32\WindowsPowerShell\v1.0> Get-DnsClientGlobalSetting


UseSuffixSearchList : True
SuffixSearchList    : {elisa.net, fr01.awl.mycorporate.net, deac.awl.mycorporate.net, wl.corp-group.net}
UseDevolution       : True
DevolutionLevel     : 0



PS C:\Windows\System32\WindowsPowerShell\v1.0> Get-DnsClientNrptGlobal

EnableDAForAllNetworks QueryPolicy SecureNameQueryFallback
---------------------- ----------- -----------------------
Disable                Disable     Disable


PS C:\Windows\System32\WindowsPowerShell\v1.0> Get-DnsClientNrptRule
PS C:\Windows\System32\WindowsPowerShell\v1.0> Get-DnsClientNrptPolicy
PS C:\Windows\System32\WindowsPowerShell\v1.0> Get-ChildItem -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DnsPolicyConfig"
PS C:\Windows\System32\WindowsPowerShell\v1.0> Get-ChildItem -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig"


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig


Name                           Property
----                           --------
NetBird-Match                  Version           : 2
                               Name              : {.ginfra.net, .ingenico.com, .giservices.io, .netbird.giservices}
                               GenericDNSServers : 100.67.255.254
                               ConfigOptions     : 8

**Comment by tobiasplagge** [comment]
Can you tell me how you solved the problem?

My DCs are accessible via a routing peer.
DNS is actually running fine, but domain availability is not there.
However, domain join does not allow user login.
For some reason my DNS is being routed incorrectly.
In order for it to work at all, I had to manually make DNS entries in the main network card.

What approach should actually work?

Thank you.

**Comment by al-dubois** [comment]
> Can you tell me how you solved the problem?
> 
> My DCs are accessible via a routing peer. DNS is actually running fine, but domain availability is not there. However, domain join does not allow user login. For some reason my DNS is being routed incorrectly. In order for it to work at all, I had to manually make DNS entries in the main network card.
> 
> What approach should actually work?
> 
> Thank you.

Any luck on your side since July 19th ? @tobiasplagge

**Comment by flotpg** [comment]
Today I tried it on a Windows 11 25H2 machine (which is only Entra ID joined, no local onprem AD join) and suddenly it's also broken there as well.
I only get DNS if I set the DNS server to match ALL domains but I don't want to push every DNS query through the tunnel.

@lixmal / @mlsmaycon do you want a debugging session?

**Comment by mlsmaycon** [comment]
@flotpg sounds good. Can you please send me an email at support@netbird.io, and I will send you a calendar link to pick a slot.

**Comment by webalexeu** [comment]
> Today I tried it on a Windows 11 25H2 machine (which is only Entra ID joined, no local onprem AD join) and suddenly it's also broken there as well.
> I only get DNS if I set the DNS server to match ALL domains but I don't want to push every DNS query through the tunnel.
> 
> @lixmal / @mlsmaycon do you want a debugging session?

Are you managing your machine using intune ?

**Comment by flotpg** [comment]
@webalexeu yes.
Entra only joined machines work fine but Hybrid-Joined (meaning AD joined) won't as outlined here:
https://github.com/netbirdio/netbird/issues/987#issuecomment-2408657648

**Comment by killmasta93** [comment]
hi guys has this been solved? having also an issue for linux machines and android or is there a workaround?

**Comment by florian-obradovic** [comment]
> hi guys has this been solved? having also an issue for linux machines and android or is there a workaround?
This is a windows specific issue, only.
